---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: latest
  http_proxy:
  https_proxy:
  no_proxy:

verifier:
  name: inspec

platforms:
  - name: centos-7.2
    driver:
      box: centos72
      box_url: file:///workdirs/packer/packer_builds/virtualbox/centos-7.2/centos-7.2-x86_64.box
  - name: ubuntu-14.04
    driver:
      box: ubuntu1404
      box_url: file:///workdirs/packer/packer_builds/virtualbox/ubuntu-14.04/ubuntu-14.04-amd64.box

suites:
  - name: rhel_docker-latest
    run_list:
      - recipe[docker-node::service]
    attributes:
      docker-node:
        version: '1.10.3'
        install_method: 'package'
        insecure_registry: nil
        http_proxy: ''
        https_proxy: ''
        no_proxy: ''
    excludes:
      - ubuntu-14.04

  - name: debian-docker
    run_list:
      - recipe[docker-node::service]
    attributes:
      docker-node:
        version: '1.10.3'
        install_method: 'package'
        insecure_registy: nil
        http_proxy: ''
        https_proxy: ''
        no_proxy: ''
    excludes:
      - centos-7
