name             'docker-node'
maintainer       'Sebastian Gerau'
maintainer_email 'gsebast@web.de'
license          'All rights reserved'
description      'Installs/Configures Docker components'
long_description 'Installs/Configures docker-node'
version          '0.1.4'

depends					 'docker', '~> 2.0'
depends          'apt-docker', '~> 0.3'
depends          'yum-docker', '~> 0.3'
